### ISSUE TITLE
Package structure built. Need to adjust save & scrape functions

### ISSUE THREAD

**Issue by DrMattG** [nealhaddaway/eejarticlemetadata#1]
The save & scrape functions need to be adjusted - error in build as it is looking for each individual part: 
Error in mapply(pdflink, doi) : object 'doi' not found
Error: unable to load R code in package 'eejarticlemetadata'

Need to encompass mapply in to the function

**Comment by nealhaddaway** [comment]
The first error is probably because you need some DOIs to work with - can we preload the DOIs from the eejarticlemetadata as default package data?
Not sure about the second error...

**Comment by nealhaddaway** [comment]
Oh wait - this is closed.. lol
